FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  capsure_web.py /home/myapp/
RUN pip install flask_sqlalchemy
RUN pip install flask_marshmallow
EXPOSE 8080
CMD python3 /home/myapp/capsure_web.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  capsure_web.py /home/myapp/
RUN pip install flask_sqlalchemy
RUN pip install flask_marshmallow
EXPOSE 8080
CMD python3 /home/myapp/capsure_web.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  capsure_web.py /home/myapp/
RUN pip install flask_sqlalchemy
RUN pip install flask_marshmallow
EXPOSE 8080
CMD python3 /home/myapp/capsure_web.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  capsure_web.py /home/myapp/
RUN pip install flask_sqlalchemy
RUN pip install flask_marshmallow
EXPOSE 8080
CMD python3 /home/myapp/capsure_web.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  capsure_web.py /home/myapp/
RUN pip install flask_sqlalchemy
RUN pip install flask_marshmallow
EXPOSE 8080
CMD python3 /home/myapp/capsure_web.py
